### PR TITLE
[#82] Allow most special characters in `name` of a user

### PR DESCRIPTION
**Pull request by sha1sum**
This addresses #82 in order to allow for non-alpha-numeric characters such as spaces, commas, periods, etc. in a user's `name` field while still keeping XSS checks.

This uses `not_regex` validation to check that there are no `<` characters in the string nor `&` characters just to be safe from any HTML entity business.

### CODE REVIEW

**Review by jeremykenedy — COMMENTED** [review]
The reason special characters are disabled is to prevent sql injection.

**Comment by sha1sum** [comment]
SQL injection prevention is handled out of the box by Eloquent afaik

**Comment by jeremykenedy** [comment]
They can still be saved and then ran on render. This change was added because at some point years and years ago I was able to do it with eloquent.

**Comment by sha1sum** [comment]
So what you're saying is that no one can make a form field with any special character allowed? I don't mean to sound combative, but this sounds pretty dismissive. I can just continue using my fork, but we can and do indeed have spaces in user names. The fact that the input on the frontend says "name" isn't even clear that it's a "username" and not the person's actual *name* name, which is what most people put in. This has been causing us no trouble whatsoever. If you're worried about SQL injection then I can try to add further prevention, but I'm getting the vibe from you that you don't really care and I should stop trying.

**Comment by jeremykenedy** [comment]
Understand, it's not about ego, vibes, or personal feelings. It's about security and not introducing a potential vulnerability. If it was proven that it would not that would one thing but this is an opinionated change request based up on the wants of your app. I cannot jeopardize the security of everyone's app based on the requirements of your app.

**Comment by jeremykenedy** [comment]
Make the PR again and I will approve it.

**Pull request closed without merging**
